### ISSUE TITLE
nsc init flags

### ISSUE THREAD

**Issue by ColinSullivan1** [nats-io/nsc#199]
I think removing some of the flags would make the user experience smoother, as was done with most of the other commands.  Most other cloud-related tooling tend to use flags to enhance commands, but generally don't require them for basic functionality - I'm thinking of docker, kubectl, etc.

For example, from using other tools, I've been trained to expect
`nsc init staging`, but the actual command is `nsc init -o staging`.

**Comment by sasbury** [comment]
i usually put a name as well as the operator, so this could be confusing:

`nsc init staging alpha` vs `nsc init alpha staging`

i think there are some places where args are "obvious" to deduce but for the commands like init where you often pass multiple flags that could be very tricky. I am not sure about init, but most commands also have an interactive mode which helps.

**Comment by aricart** [comment]
I agree no flags are easier - except that you then have positional arguments which now introduces an ambiguity. the purpose of the flags is to tag the argument. I have yielded a bit on the add/describe type commands. But at least in those cases, you are specifying the thing you are adding. The init command was originally exposed so that ngs could do what it did. In terms of ngs now, I would rather we always suggest `nsc add operator -u <url>` - in the case of the ngs documentation - we also support well known operators so they can do `nsc add operator -u synadia`.
