### ISSUE TITLE
Having minor issue with tutorial example nats-account-server and nsc push

### ISSUE THREAD

**Issue by paul42** [nats-io/nsc#289]
trying to make a new user and push to nats-account-server, all localhost, from this tutorial here: https://docs.nats.io/nats-tools/nas/notifications

but I'm getting: 
```
[nats-admin@nats-proto-3 ~]$ nsc push -a system
[ERR ] push system to account server:
       [ERR ] failed to push account to remote server
       > Method Not Allowed
```
which I think is this error here? https://github.com/nats-io/nsc/blob/c63680c9e1dd37508d9df6abeb1c6c6f89d84f12/cmd/store/status.go#L372

what's the best way to debug this? it's all on one vm, and I can see my nats-account-server and nats-server running and communicating with each other

also what's the best clustering strategy for nats-account-server to have one primary and others replicate?

Thanks in advance!

**Comment by paul42** [comment]
added my nats-server.config and nats-account-server.config in a gist here: https://gist.github.com/paul42/62c820b4224b4dffedba2fc16fed7b56

thanks for your help in advance

**Comment by aricart** [comment]
Yes! - the nsc store will not allow you to push to it. You need to install a full account server if you want to push to it.

**Comment by aricart** [comment]
The tutorial is showing you a directory store.
```
operatorjwtpath: "/users/synadia/.nsc/nats/AAA/AAA.jwt",
systemaccountjwtpath: "/users/synadia/.nsc/nats/AAA/accounts/SYS/SYS.jwt"
http {
    port: 9090
},
store {
    dir: "/tmp/as_store",
    readonly: false,
    shard: true
}
nats {
  servers: [nats://localhost:4222]
  usercredentials: "/Users/synadia/.nkeys/AAA/accounts/SYS/users/sys.creds"
}
```

**Comment by paul42** [comment]
Hey @aricart thanks for the fast response! So just to double check my understanding, if I want to be able to use the nsc tool to manage the permissions (say a new team wants to onboard, and I already have an account with good permissions set, just need to make a new user) would I just configure the account server to serve a directory and still use nsc add user and nsc push?

**Comment by aricart** [comment]
NSC store is only useful for local testing.  The user JWTs only need to be issued. The account servers don't store user jwts, since users are just verified by the user signing a nonce and by verifying that the issuer account is trusted by the operator. 

If your account don't change often, you'll just want to specify a memory resolver in the server configuration. That removes a server piece and simplifies your configs. 

NSC can generate a config file with a memory resolver and.all the accounts for your local operator.

**Comment by aricart** [comment]
See this for generating.  https://nats-io.github.io/nsc/nsc_generate_config.html

**Comment by paul42** [comment]
Awesome, thanks again @aricart the more I learn about the nats ecosystem the more sense it makes, I'm not an expert by any stretch but it's mostly clicking and I'm excited to try this method out, in my imagined scenario we would not be making changes rapidly so this seems to be a great fit

**Comment by paul42** [comment]
@aricart thanks for your help I got the generated config working perfectly! I was wondering if there's a better place to ask operational questions, is there a forum or discord? my main question is, if we're running fine, but one day, the vm we started with needs to be rotated, how can I export the nsc config / directory easily and then restore it on a new vm? is it as simple as just making a directory that contains the .nsc and .nkeys and backing that up to a private git repo? I noticed the nsc export keys just does the nkeys, which doesn't look liek it has the jwt info like .nkeys/creds/etc..../system.creds would have - what do you pros do?

Thanks again, and sorry for the deluge of questions 😅

**Comment by aricart** [comment]
@paul42, not a problem - for questions you will want to join our [slack](https://slack.nats.io/)
Yes the entire set of configurations is on the `.nsc` and `.nkeys`. Note that the `.nsc` directory is really mapped to a specific user. If you are putting some of this stuff somewhere where it is shared, you'll want to define these locations in your environment variables.

`$NKEYS_PATH` is the directory where you keep your secret keys (`.nkeys` dir)
The directory that contains your operators  is the _Stores Dir_, by default this is in `~/.nsc/nats`. You can move this last directory and put it anywhere you want.

When using nsc, you can specify where the default store directory is by doing:
`nsc env --store <dir>`. This will save it to your ~/.nsc home, so that you don't have to re-enter it. You can also view all these magic values in `nsc env`.

So if you were using an account server, you would have your 'source' JWTs somewhere and use nsc to edit them. If your operator has an account jwt server URL set, it will automatically push any changes to your account there.

If you are using a memory resolver, really all you have to do is `nsc generate config` as we talked earlier.  That file embeds the current operator and all account JWTs in that tree.
For your processes, simply configure them to use the generated creds files.
