### ISSUE TITLE
describe jwt --json/--raw are not honored

### ISSUE THREAD

**Issue by aricart** [nats-io/nsc#319]

**Comment by bruth** [comment]
I tried `nsc describe account A --field sub` and this returns the JSON encoded value (with the quotes) rather than the raw value, e.g. `"ACDS284D..."` vs. `ACDS284D...`. This prevents a use case of doing something like:

```
nsc add import \
    --account B \
    --src-account $(nsc describe account A --field sub) \
    --remote-subject "foo.bar.>" \
    --local-subject "A"
```

Since the quotes are escaped and treated as part of the account public key in the command. I am currently stripping the quotes using `jq -r`, e.g. `$(nsc describe account A --field sub | jq -r)`, but it seems like it would make more sense to decode the JSON value when individual fields are accessed.

**Comment by aricart** [comment]
@bruth the issue here is that the json value of a string is really a quoted value. For identities or references like this, what would be useful is to get the public key of the entity itself - it would still an invocation in the subshell as you have it. Possibly `--src-account-name` would be more useful in this case.

**Comment by bruth** [comment]
@aricart Yes understood that the value is quoted since it is being extracted from a JSON object. My suggestion was more around whether it should be decoded by default since the option `--field` is pulling out a single value anyway. In other words, what was the original use case for pulling out a specific field that remains JSON-encoded?

In any case, if a new option `--src-account-name` is added, that would solve the problem also. Thanks!
